app = "full-stack-open-pokedex-12345"
primary_region = "lax"

[processes]
  app = "node app.js"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# Can't use bluegreen deployment strategy because a payment method is required
# [deploy]
#   strategy = "bluegreen"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
